adds an install script for aescrypt Rust
danielpclark/abrute pull request #8
Opened 2017-10-07 16:22 UTC by baptistecolin

Adds an `install.sh` shell script which retrieves aescrypt and Rust.
If the script is hosted at `www.myadress.com/path`, then it can be executed by firing the following command :

`curl www.myadress.com/path | sh`

Should the script also execute 
`cargo build --release`
`sudo cp target/release/abrute /usr/bin/` ?

2017-10-07 23:08 UTC, danielpclark commented
@baptistecolin The install script should work as follows:

* First — check if Rust is installed or not.  If it is installed skip to next step.  If not notify the user that Rust needs to be installed to continue and ask if they want to continue.  If they say yes install Rust.  If no stop the installation.
* Second — check is aescrypt is installed or not.  If not install it.
* Third — download abrute source code, eun `cargo build release` and `sudo cp target/release/abrute /usr/bin/`
* Fourth — Say “Thank you for installing abrute!  Enjoy!”

2017-10-08 13:31 UTC, baptistecolin commented
Here you go, now it should only install Rust and/or Aescrypt if they are not already installed. Then it should carry on with the rest of the installation, making Abrute ready to be used.

Let me now if you had something else in mind

2017-10-08 22:34 UTC, danielpclark commented
It looks really good so far!  Thanks…  Two more things.  For `aescrypt` installation we don't need to ask the user for permission, it's an extremely small dependency so we'll install it without asking if it's not installed.  It's understood that that is a dependency and we only need one confirmation for proceeding with the install.

And lastly the last step only works if a person is in the current project directory with all of the source files.  So if they wanted to install it like Rust is installed with `curl install-script-from-url | sh` then they wouldn't have the files to run `cargo build --release` with.

So for the `abrute` install part it should check if the folders `.git` and `src` exist before doing what you have.  If those folders don't exist the download `https://github.com/danielpclark/abrute/archive/master.zip` with `wget`, extract, go into the directory, run the commands you have, then exit the directory and remove the installation files.

2017-10-09 09:41 UTC, baptistecolin commented
Here you go, I tried it on my machine and launching `./install.sh` installs Abrute from scratch !
Just one thing, due to some syntax tricks I used, `curl install-script-url | sh` wouldn't work. Please use `curl install-script-url | bash` instead.

2017-10-09 09:54 UTC, danielpclark requested changes
Line 33 looks to be an uncommented comment which as far as I know won't work in a shell script

2017-10-09 09:54 UTC, danielpclark commented on install.sh
> +    User agreed, proceed with installation
Should this be a comment here?

2017-10-09 10:01 UTC, baptistecolin commented on install.sh
> +    User agreed, proceed with installation
Absolutely

2017-10-09 10:02 UTC, danielpclark commented
Hey, I'm just curious about this one part now `== $rustc_prefix*` … I've never seen an asterisk on the end of a bash variable before.  Is this another way of executing the string for the output from the command?

2017-10-09 10:06 UTC, merged

2017-10-09 10:07 UTC, danielpclark commented
Excellent work @baptistecolin ! :tada:

2017-10-09 10:12 UTC, baptistecolin commented
In this particular case, the expression is between brackets : `[[ $rust_install_status == $rustc_prefix* ]]`
I'm testing if the first string matches a certain pattern.
If Rust is installed, then `$rust_install_status` will be something like `rustc 1.20.0 (f3d6973f4 2017-08-27)`. If it's not, then it will be something like "The "rustc" command could't be found [...]".
So, if `rustc` is a prefix of `$rust_install_status`, it means Rust is installed.
I defined `$rustc_prefix` to be equal to `rustc`. Adding a `*` after means "whatever after `$rustc_prefix` is ok". This way, if `$rust_install_prefix` starts with "rustc", the test will return true and the if/then/else statement will do what I want :)

2017-10-09 10:14 UTC, danielpclark commented
Got it.  Thanks for letting me know.